# Generated by Django 6.0.1 on 2026-04-16 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='id_material',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Material_ID'),
        ),
    ]
